name: Publish yew frontend to github pages

on: [push]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Get wasm target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Get trunk
        uses: jetli/trunk-action@v0.4.0
      - name: Get wasm-bind-gen
        uses: jetli/wasm-bindgen-action@v0.1.0
      - name: Install lftp
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: lftp
          version: 1.0

      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cd yew && trunk build  --release
      - name: Deploy

        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./yew/dist

      - name: Deploy to strato
        shell: bash
        env:
          STRATO_FTP_PASSWORD: ${{ secrets.STRATO_FTP_PASSWORD }}
        run: |
          : # copy the index.html to language subdirectories is required due to the web server settings at strato
          mkdir -p yew/dist/de
          cp yew/dist/index.html yew/dist/de/
          mkdir -p yew/dist/ch
          cp yew/dist/index.html yew/dist/ch/
          mkdir -p yew/dist/en
          cp yew/dist/index.html yew/dist/en/
        run:  lftp -u homepage@almedso.de,$STRATO_FTP_PASSWORD -e "set sftp:auto-confirm yes; mirror -X .* -X .*/ --reverse --verbose --delete yew/dist/ /wordclock/; quit" sftp://ssh.strato.de

