name: Publish yew frontend to github pages

on: [push]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Get wasm target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Get trunk
        uses: jetli/trunk-action@v0.4.0
      - name: Get wasm-bind-gen
        uses: jetli/wasm-bindgen-action@v0.1.0

      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cd yew && trunk build  --release --config Trunk4GhPages.toml
      - name: Deploy

        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./yew/dist

